"""Initial Migrate

Revision ID: 4f191ffd7f8d
Revises: 
Create Date: 2023-05-22 23:28:51.919340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f191ffd7f8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('periodicity', sa.String(length=10), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('times_broken', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_date_time'), ['date_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_date_time'))

    op.drop_table('habit')
    # ### end Alembic commands ###
